CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(512) UNIQUE NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(512),
    user_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (request_id),
    foreign key (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    is_available BOOL NOT NULL,
    user_id BIGINT,
    request_id BIGINT,
    PRIMARY KEY (item_id),
    foreign key (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    foreign key (request_id) REFERENCES requests (request_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'),
    PRIMARY KEY (booking_id),
    foreign key (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    foreign key (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (comment_id),
    foreign key (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    foreign key (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);